Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.box = "generic/ubuntu2004"
      server.vm.hostname = "server#{i}"
      
      # Configuration spécifique au fournisseur VMware Workstation
      server.vm.provider "vmware_workstation" do |vmw|
        vmw.memory = 1024
        vmw.cpus = 1
      end
    end
  end
end
