# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "server#{i}" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "server#{i}"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
      vb.name = "server#{i}"
      end
    end
  end
end
